# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('btor-example', ['btor','core','network', 'internet', 'point-to-point', 'point-to-point-layout', 'applications'])
    obj.source = 'btor-example.cc'
   
