# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('btor', ['core'])
    module.source = [
        'model/tor-base.cc',
        'model/tor.cc',
        'model/tokenbucket.cc',
        'model/pseudo-socket.cc',
        'model/cell-header.cc',
        'helper/branched-tor-dumbbell-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('btor')
    module_test.source = [
        #'test/btor-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'btor'
    headers.source = [
        'model/tor-base.h',
        'model/tor.h',
        'model/tokenbucket.h',
        'model/pseudo-socket.h',
        'model/cell-header.h',
        'helper/branched-tor-dumbbell-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

